### ISSUE TITLE
Local installation: Internal server error on second review after revision

### ISSUE THREAD

**Issue by rtnieuwboer** [thehyve/podium#279]
When i have send a request for revision and try to send for a new review i get an internal server error in the UI and in the postgresql log an error for unique key constraint (review_round_request_detail_key) on the table review_round in podiumGateway. Can this error be fixed?

**Comment by gijskant** [comment]
Thanks for the bug report. I have trouble reproducing the issue. I tried the following sequence:
- Researcher creates request, fills the form and submits
- Coordinator validates and sends to reviewers
- Reviewer adds evaluation (Reject)
- Coordinator sends the request back for revision
- Researcher adjusts the request and resubmits
- Coordinator validates and sends to reviewers
- Reviewer adds evaluation (Approve)
- Coordinator approves the request

Could you add a detailed description of the steps leading to the error? And perhaps a screenshot of the error state?

**Comment by rtnieuwboer** [comment]
Hoi Gijs, leuk dat je antwoord. Ik zal het morgen nogmaals proberen. Kan even duren want mijn VM is vanavond gecrashed. Gr Rene.

Verzonden vanuit Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by gijskant** [comment]
Hoi René,

Could you test with the current `dev` branch or version `1.0.1-SNAPSHOT` from the snapshots repository (e.g., if you are using the Puppet module)?
The problem should be fixed, but may require to first send the request to revision once more. Then the 'request details' are copied into a new unique record for the next review round, and the request can be submitted.

Kind regards,
Gijs
